// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdrqaurowkqsqnqgweog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcnFhdXJvd2txc3FucWd3ZW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTcxMzIsImV4cCI6MjA2NDQ3MzEzMn0.n_cgu3gh8DXEoFb7u4SlVBesoovJ0Y68Oe2dzUiAePE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);